server:
  port: 1120

spring:

  application:
    # 服务注册时使用的名称
    name: User-Server-Service

  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # MySQL 驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    # 数据库链接
    url: jdbc:mysql://localhost:3306/AlanDeviseDatabase?useUnicode=true&characterEncoding=utf8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    # 用户名
    username: root
    # 密码
    password: AlanDevise2020
    druid:
      # 关闭数据库连接空闲检测，频繁检测会降低性能
      test-while-idle: false

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    #    password: AlanDevise2020 # 如果未单独配置默认为空即可
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  output:
    ansi:
      # 设置控制台输出高亮
      enabled: always

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
