server:
  port: 9001

spring:
  application:
    name: Payment-Provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true

logging:
  level:
    root: info
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: "*"