server:
  # 服务端口号
  port: 9001

spring:
  application:
    # 服务注册时使用的名称[使用Nacos时，服务名称一定要和配置中心一样写在bootstrap，否则会被解析成null.properties或null.yaml]
    name: Payment-Provider
  cloud:
    nacos:
      # 服务发现地址
      server-addr: 127.0.0.1:8848
      # 配置中心地址
      config:
        server-addr: 127.0.0.1:8848
        namespace: b5c78034-8d70-409d-af6e-62fe1b798ef7
        extension-configs:
          # 服务特有配置
          # 数据源公共配置
          - data-id: datasource.yaml
            refresh: true
          # Redis公共配置
          - data-id: redis-config.yaml
            refresh: true
          # Mybatis-plus公共配置
          - data-id: mybatis-plus-config.yaml
            refresh: true

logging:
  level:
    root: info
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

# dubbo配置
dubbo:
  scan:
    base-packages: com.alandevise.PaymentProvider.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  provider:
    loadbalance: leastactive
    dispatcher: message
    threadpool: cached
    timeout: 60000
    delay: -1
  application:
    dump-directory: ./tmp