server:
  port: 1124

spring:
  application:
    name: MultiTSDB-Server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

tsdb:
  default-type: iotdb
  default-database: cloud_platform
  iotdb:
    enabled: true
    host: 127.0.0.1
    port: 6667
    username: root
    password: root
    use-table-model: false
  tdengine:
    enabled: true
    host: 127.0.0.1
    port: 6041
    username: root
    password: taosdata

logging:
  level:
    com.alandevise.multitsdb: DEBUG
    org.apache.iotdb: INFO
    com.taosdata.jdbc: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
