server:
  port: 1883

spring:
  application:
    name: MQTT-Server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true

logging:
  level:
    root: info
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

## MQTT##
mqtt:
  host: tcp://localhost:1883
  userName: root
  passWord: 123456
  qos: 1
  clientId: ClientId_local
  timeout: 10
  keepalive: 20
  topic1: A/pick/warn/#  #符号是代表整个warn下面的全部子主题 没有理解的话 可以百度仔细理解一下
  topic2: A/cmd/resp
  topic3: ABCF
  topic4: ABCH
