server:
  port: 1118

spring:

  application:
    # 服务注册时使用的名称
    name: General-Server-Service

  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # MySQL 驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    # MySQL数据库链接
    url: jdbc:mysql://localhost:3306/AlanDeviseDatabase?useUnicode=true&characterEncoding=utf8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    # MySQL用户名
    username: root
    # MySQL密码
    password: AlanDevise2020
    druid:
      # 关闭数据库连接空闲检测，频繁检测会降低性能
      test-while-idle: false
  #    # PostgresSQL 配置
  #    url: jdbc:postgresql://localhost:5432/postgres
  #    # postgresSQL用户名
  #    username: postgres
  #    # PostgresSQL密码
  #    password: My123
  #    # PostgresSQL 驱动包
  #    driver-class-name: org.postgresql.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 32768
    password: redispw # 如果未单独配置默认为空即可
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  output:
    ansi:
      # 设置控制台输出高亮
      enabled: always

  mvc:
    pathmatch:
      # 解决Swagger3找不到路径
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.alandevise.dao.StudentMapper: debug
    org:
      apache:
        ibatis:
          executor: debug