server:
  tomcat:
    connection-timeout: 5000
  port: 1121
spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/AlanDeviseDatabase?useUnicode=true&characterEncoding=utf8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: root
      password: AlanDevise2020
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://localhost:55002/AlanDeviseDatabase?useUnicode=true&characterEncoding=utf8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: root
      password: AlanDevise2020
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG # 将hikari的日志级别设置为debug级别，以看清其运行的逻辑
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: AUTO
      insert-strategy: NOT_NULL
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true

