server:
  port: 9002
spring:
  application:
    name: Payment-Consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # MySQL 驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    # MySQL数据库链接
    url: jdbc:mysql://localhost:3306/AlanDeviseDatabase?useUnicode=true&characterEncoding=utf8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    # MySQL用户名
    username: root
    # MySQL密码
    password: AlanDevise2020
    druid:
      # 关闭数据库连接空闲检测，频繁检测会降低性能
      test-while-idle: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 55000
    password: redispw # 如果未单独配置默认为空即可
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  mvc:
    pathmatch:
      # 解决Swagger3找不到路径
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: "*"